export const seedConfessions = [
  // ROMANCE (1–15)
  { category: "relationship", content: "I pretend I’m over her but I still check her WhatsApp last seen every night." },
  { category: "relationship", content: "I love my girlfriend, but I think I fell harder for who she was at the beginning." },
  { category: "relationship", content: "I said “I’m busy” but I just didn’t want to talk to him anymore." },
  { category: "relationship", content: "I stayed in a relationship 2 years longer than I should have because I was scared to start over." },
  { category: "relationship", content: "I met someone online and I feel more connected to them than anyone in my real life." },
  { category: "relationship", content: "I still remember the exact way he said my name. No one has said it like that since." },
  { category: "relationship", content: "I blocked her everywhere but I still know her number by heart." },
  { category: "relationship", content: "I think I love the idea of love more than actual relationships." },
  { category: "relationship", content: "I cheated once. I’ve never told anyone. It still eats me up." },
  { category: "relationship", content: "I let him go because I thought he deserved better. Now I regret it every day." },
  { category: "relationship", content: "I’m in a relationship but I miss being single sometimes." },
  { category: "relationship", content: "I said “I’m fine” but I wanted him to fight for me." },
  { category: "relationship", content: "I married the safe option, not the one I loved the most." },
  { category: "relationship", content: "I stalk my ex’s new partner more than I should." },
  { category: "relationship", content: "I think the person I loved the most will never know." },
  
  // ADULT (16–30)
  { category: "sexual", content: "I act confident but I feel insecure about my body every single day." },
  { category: "sexual", content: "I’ve stayed in situations just because I didn’t want to be alone." },
  { category: "sexual", content: "I regret my first time. I wish I waited." },
  { category: "sexual", content: "I sometimes feel like people only value me for what I can give them physically." },
  { category: "sexual", content: "I’ve pretended to enjoy moments just to not hurt someone’s feelings." },
  { category: "sexual", content: "I compare myself to people online and it messes with my head." },
  { category: "sexual", content: "I once stayed with someone because they made me feel “wanted,” not loved." },
  { category: "sexual", content: "I’ve said yes when I meant no." },
  { category: "sexual", content: "I think I’ve confused attention for affection too many times." },
  { category: "sexual", content: "I wish I understood my own boundaries earlier in life." },
  { category: "sexual", content: "I feel like I’ve lost parts of myself trying to please others." },
  { category: "sexual", content: "I’ve been with people I didn’t even like that much." },
  { category: "sexual", content: "I sometimes wonder if I even know what real intimacy feels like." },
  { category: "sexual", content: "I let someone cross a line because I didn’t want conflict." },
  { category: "sexual", content: "I still carry shame from things I did years ago." },

  // DARK (31–45)
  { category: "dark", content: "I smile a lot but I’m not okay most of the time." },
  { category: "dark", content: "I feel like nobody actually knows the real me." },
  { category: "dark", content: "I’ve lost motivation for everything but I keep pretending." },
  { category: "dark", content: "I sometimes feel like I’m just existing, not living." },
  { category: "dark", content: "I push people away before they can leave me." },
  { category: "dark", content: "I don’t trust happiness. It never lasts." },
  { category: "dark", content: "I’ve cried in places where no one could see me." },
  { category: "dark", content: "I feel like I’m behind in life compared to everyone else." },
  { category: "dark", content: "I laugh in public and feel empty in private." },
  { category: "dark", content: "I’ve had thoughts that scared me, so I never told anyone." },
  { category: "dark", content: "I feel like a burden even when people say I’m not." },
  { category: "dark", content: "I keep everything inside until it explodes." },
  { category: "dark", content: "I don’t remember the last time I felt truly at peace." },
  { category: "dark", content: "I’m tired, but not physically." },
  { category: "dark", content: "I wish I could restart my life without losing my memories." },

  // WORK (46–60)
  { category: "work", content: "I act like I know what I’m doing at work, but I’m figuring it out daily." },
  { category: "work", content: "I’ve applied for jobs during office hours using my company WiFi." },
  { category: "work", content: "I don’t like my boss, but I pretend I do." },
  { category: "work", content: "I feel underpaid but too scared to ask for more." },
  { category: "work", content: "I’ve taken credit for something I didn’t fully do." },
  { category: "work", content: "I’m burnt out but I can’t afford to quit." },
  { category: "work", content: "I hate Mondays more than I admit." },
  { category: "work", content: "I sometimes delay work on purpose just to feel in control." },
  { category: "work", content: "I feel like I chose the wrong career path." },
  { category: "work", content: "I smile in meetings and complain right after." },
  { category: "work", content: "I’ve thought about quitting dramatically more than once." },
  { category: "work", content: "I compare my salary with my friends and feel bad." },
  { category: "work", content: "I’ve lied on my CV." },
  { category: "work", content: "I’m scared someone will realize I’m not as good as they think." },
  { category: "work", content: "I stay late at work sometimes just to avoid going home." },

  // FAMILY (61–75)
  { category: "family", content: "I love my family, but I don’t like being around them sometimes." },
  { category: "family", content: "I feel like the “responsible one” and it’s exhausting." },
  { category: "family", content: "I hide things from my parents because they wouldn’t understand." },
  { category: "family", content: "I wish my parents said “I’m proud of you” more." },
  { category: "family", content: "I feel closer to strangers than my own siblings." },
  { category: "family", content: "I’ve lied about how I’m doing just to avoid worrying them." },
  { category: "family", content: "I carry expectations that were never spoken out loud." },
  { category: "family", content: "I feel like I have to succeed for everyone, not just myself." },
  { category: "family", content: "I envy families that seem peaceful." },
  { category: "family", content: "I avoid going home because of tension." },
  { category: "family", content: "I feel like I’m living the life my parents wanted, not mine." },
  { category: "family", content: "I wish we talked more honestly in my family." },
  { category: "family", content: "I sometimes feel invisible at home." },
  { category: "family", content: "I’ve forgiven things I never got an apology for." },
  { category: "family", content: "I wish I could reset my relationship with my parents." },

  // FUNNY (76–90)
  { category: "funny", content: "I waved back at someone who wasn’t waving at me." },
  { category: "funny", content: "I confidently gave wrong directions and just kept walking." },
  { category: "funny", content: "I laughed at a joke I didn’t understand." },
  { category: "funny", content: "I tried to push a “pull” door… multiple times." },
  { category: "funny", content: "I sent a message to the wrong person and pretended it was intentional." },
  { category: "funny", content: "I practiced an argument in my head and lost." },
  { category: "funny", content: "I opened my camera by mistake and scared myself." },
  { category: "funny", content: "I replied “you too” when a waiter said “enjoy your meal.”" },
  { category: "funny", content: "I refreshed an app like 20 times expecting new notifications." },
  { category: "funny", content: "I typed a long message and deleted it." },
  { category: "funny", content: "I checked my phone while it was already in my hand." },
  { category: "funny", content: "I nodded like I understood what someone said. I didn’t." },
  { category: "funny", content: "I’ve laughed just to end awkward silence." },
  { category: "funny", content: "I googled something basic because I forgot." },
  { category: "funny", content: "I said “I’m on my way” while still at home." },

  // OTHER (91–100)
  { category: "other", content: "I feel more like myself online than in real life." },
  { category: "other", content: "I’ve changed my personality depending on who I’m with." },
  { category: "other", content: "I wonder how people perceive me when I’m not around." },
  { category: "other", content: "I wish I had the courage to start over in a new country." },
  { category: "other", content: "I’ve pretended to be okay just to avoid questions." },
  { category: "other", content: "I feel like I have potential but I’m not using it." },
  { category: "other", content: "I compare my life to people I don’t even know." },
  { category: "other", content: "I sometimes miss people I’ve never met." },
  { category: "other", content: "I wish I could see my life from someone else’s perspective." },
  { category: "other", content: "I’m still figuring out who I am." },

  // LONG RAW CONFESSIONS (HIGH-ENGAGEMENT)
  { category: "relationship", content: "I’m in a relationship with someone who genuinely loves me, and I know that. They check on me, they support me, they try. But I don’t feel the same way anymore. I’ve been pretending for months because I don’t want to be the bad person. Every time they say “I love you,” I say it back… and I feel guilty immediately after. I don’t know how to leave without destroying them." },
  { category: "relationship", content: "There’s someone I talk to every day online. We’ve never met, don’t even live in the same country, but they know more about me than anyone in my real life. Sometimes I catch myself wishing they were the one I wake up next to. The scary part is… I think I’m more emotionally attached to them than to the person I’m actually dating." },
  { category: "dark", content: "I act confident, like I have everything under control, but the truth is I constantly feel like I’m behind in life. My friends are moving forward—jobs, relationships, progress—and I’m just… here. Smiling in pictures, posting like everything is fine, but deep down I feel like I’m wasting my life and I don’t know how to fix it." },
  { category: "dark", content: "I’ve stayed in situations I knew weren’t good for me just because I didn’t want to feel alone. Not because I was happy. Not because it was right. Just because silence scares me more than anything else. I think I’ve confused “not being alone” with “being loved” for a long time." },
  { category: "relationship", content: "I still think about someone I haven’t spoken to in years. Not every day, but randomly, something reminds me of them and it hits hard. We didn’t even end badly… life just happened. But sometimes I wonder what my life would look like if I had made one different decision back then." },
  { category: "dark", content: "I lie about how I’m doing all the time. It’s easier to say “I’m good” than to explain everything going on in my head. People think I’m strong, but really I just don’t know how to open up without feeling like I’m being dramatic or too much." },
  { category: "dark", content: "I’ve achieved things I once prayed for, and somehow I’m still not happy. That realization scared me. Because if getting what I wanted didn’t fix anything, then what will?" },
  { category: "dark", content: "I sometimes replay conversations in my head and think of all the things I should have said. It’s like I live my life twice—once in real time, and once in regret." },
  { category: "dark", content: "There are parts of my personality I only show certain people. No one actually knows the full version of me. Not my friends, not my family. I’ve built different versions of myself depending on who I’m around, and now I don’t even know which one is real anymore." },
  { category: "dark", content: "I’ve hurt people who didn’t deserve it, just because I was dealing with things I didn’t understand at the time. I never apologized. Not because I didn’t care, but because I didn’t know how to face what I did." },
  { category: "dark", content: "Sometimes I distance myself from people on purpose, just to see if they’ll notice. Most of the time… they don’t." },
  { category: "dark", content: "I’m scared that I’m becoming someone I wouldn’t have respected a few years ago. Not in a big obvious way, just slowly… small decisions, small compromises. And now I don’t even know when it started." },
  { category: "dark", content: "I’ve compared myself to people online so much that I’ve started feeling like my own life isn’t enough. Even when nothing is actually wrong." },
  { category: "dark", content: "I’ve been the “strong one” for so long that I don’t even know how to ask for help anymore. People come to me with their problems, but I don’t have anyone I feel comfortable going to with mine." },
  { category: "dark", content: "There’s something I’ve been carrying for years that I’ve never told anyone. Not because I can’t, but because once I say it out loud, it becomes real. And I don’t think I’m ready for that." },
  { category: "dark", content: "I’ve stayed quiet in situations where I should have spoken up, just to keep peace. Now I carry the frustration alone." },
  { category: "dark", content: "I sometimes feel like I’m living a life that looks good from the outside but feels empty on the inside." },
  { category: "dark", content: "I’ve lost interest in things I used to love, and I don’t know how to get that version of myself back." },
  { category: "dark", content: "I push people away when they get too close, and then feel lonely when they leave. I don’t even know why I do it anymore." },
  { category: "dark", content: "I wonder if the people in my life would still treat me the same if they knew everything about me." },

  // INKOGNITO — DEEP CONFESSIONS (REGION-SPECIFIC)
  // NIGERIA
  { category: "relationship", content: "I was doing NYSC and got close to someone in the office. It started as harmless conversations, then late-night chats. We both knew it wasn’t supposed to go further, but we didn’t stop. Now service year is over and we don’t talk anymore, but I still think about what we almost became." },
  { category: "family", content: "My parents think I’m doing well because I don’t tell them the truth. I send pictures, I smile, but some days I don’t even have motivation to get out of bed." },
  { category: "family", content: "I’m the one everyone calls “successful” in my family, but I feel like I’m carrying everyone and slowly losing myself." },
  { category: "relationship", content: "I once had feelings for someone in my church. I never acted on it because I didn’t want to “look bad,” but I still wonder what would have happened." },
  { category: "relationship", content: "I stay in my relationship because leaving would cause too many questions at home." },
  { category: "work", content: "I’ve lied about my income just so people respect me more." },
  { category: "other", content: "I sometimes wish I could disappear and start fresh in another country where no one knows me." },
  { category: "dark", content: "I’ve pretended to be okay with things that hurt me deeply, just to avoid drama." },
  { category: "relationship", content: "I still remember someone I met during service year like it was yesterday. We didn’t even date, but it felt like something real." },
  { category: "other", content: "I’ve changed parts of myself just to fit into a friend group." },
  { category: "family", content: "I feel like I’m living two different lives—one my family sees, and one that’s actually real." },
  { category: "dark", content: "I’ve stayed quiet about things that should have been addressed, and now they’ve built up into resentment." },
  { category: "sexual", content: "I’ve been in situations that blurred lines I told myself I’d never cross." },
  { category: "dark", content: "I sometimes feel like expectations in this country are heavier than I can carry." },
  { category: "dark", content: "I’ve said yes to things I wasn’t fully comfortable with, just to not seem “difficult.”" },
  { category: "work", content: "I wonder if I’m chasing success or just running from failure." },
  { category: "dark", content: "I’ve kept secrets that would completely change how people see me." },
  { category: "relationship", content: "I’ve walked away from something meaningful because I was scared of where it would lead." },
  { category: "dark", content: "I act strong, but I break down when I’m alone." },
  { category: "dark", content: "I don’t think anyone truly knows the version of me that exists at night." },

  // UNITED STATES
  { category: "other", content: "I built a version of myself online that people admire, but it’s not who I really am." },
  { category: "relationship", content: "I’ve been in relationships where I stayed longer than I should have because I didn’t want to be alone." },
  { category: "relationship", content: "I’ve crossed emotional boundaries with someone while still committed to someone else." },
  { category: "relationship", content: "I think I’ve mistaken validation for connection too many times." },
  { category: "dark", content: "I’ve had moments where I questioned everything about who I am, but I never said it out loud." },
  { category: "other", content: "I’ve let people assume things about me because correcting them felt harder." },
  { category: "relationship", content: "I’ve chased people who didn’t treat me right, and ignored the ones who did." },
  { category: "dark", content: "I’ve said “it’s fine” so many times that I don’t even know when it actually is." },
  { category: "dark", content: "I’ve stayed in toxic cycles because they felt familiar." },
  { category: "relationship", content: "I’ve had connections that felt intense but disappeared overnight." },
  { category: "dark", content: "I’ve compared my life to others online until I started feeling like I was failing." },
  { category: "dark", content: "I’ve hidden parts of myself because I didn’t think they’d be accepted." },
  { category: "dark", content: "I’ve been in situations where I knew better, but did it anyway." },
  { category: "dark", content: "I’ve felt alone in rooms full of people." },
  { category: "other", content: "I’ve questioned whether I’m living authentically or just performing." },
  { category: "relationship", content: "I’ve avoided difficult conversations until they became bigger problems." },
  { category: "other", content: "I’ve wanted to start over but didn’t know where to begin." },
  { category: "dark", content: "I’ve built walls so high that even I can’t get out sometimes." },
  { category: "relationship", content: "I’ve lost people not because we fought, but because we stopped trying." },
  { category: "dark", content: "I’ve had moments where everything looked perfect but felt empty." },

  // INDIA
  { category: "family", content: "My family thinks I’ll follow the path they’ve planned for me, but I don’t even know if it’s what I want." },
  { category: "relationship", content: "I’ve hidden relationships because I knew they wouldn’t be accepted." },
  { category: "family", content: "I’ve stayed silent about things that mattered just to keep peace at home." },
  { category: "other", content: "I’ve felt torn between who I am and who I’m expected to be." },
  { category: "other", content: "I’ve made decisions based on fear of judgment, not what I truly wanted." },
  { category: "other", content: "I’ve pretended to agree with things I don’t believe in." },
  { category: "dark", content: "I’ve carried pressure that no one openly talks about." },
  { category: "relationship", content: "I’ve walked away from something meaningful because it felt “impossible.”" },
  { category: "dark", content: "I’ve built a life that looks right on paper but doesn’t feel right inside." },
  { category: "dark", content: "I’ve questioned whether happiness is something I can choose." },
  { category: "dark", content: "I’ve felt like I was living for everyone else except myself." },
  { category: "other", content: "I’ve hidden parts of my identity to avoid conflict." },
  { category: "relationship", content: "I’ve stayed in situations longer than I should have out of obligation." },
  { category: "family", content: "I’ve struggled with expectations that feel impossible to meet." },
  { category: "work", content: "I’ve chosen stability over passion and still wonder “what if.”" },
  { category: "dark", content: "I’ve felt misunderstood even by people closest to me." },
  { category: "dark", content: "I’ve carried emotions I don’t know how to express." },
  { category: "other", content: "I’ve avoided decisions because of fear of consequences." },
  { category: "other", content: "I’ve questioned my own choices more than I admit." },
  { category: "other", content: "I’ve wanted freedom but didn’t know how to take it." },

  // EUROPE
  { category: "other", content: "I’ve moved cities to escape something, but it followed me mentally." },
  { category: "relationship", content: "I’ve had relationships that felt right but ended anyway." },
  { category: "other", content: "I’ve built independence, but sometimes I miss having someone to rely on." },
  { category: "relationship", content: "I’ve chosen distance over confrontation too many times." },
  { category: "dark", content: "I’ve felt disconnected even in moments that should feel meaningful." },
  { category: "other", content: "I’ve prioritized logic over emotions and regretted it later." },
  { category: "relationship", content: "I’ve kept things casual because commitment felt too heavy." },
  { category: "relationship", content: "I’ve ended things before they could get complicated." },
  { category: "dark", content: "I’ve struggled with feeling truly understood." },
  { category: "relationship", content: "I’ve had connections that were intense but short-lived." },
  { category: "dark", content: "I’ve kept parts of myself guarded even with close people." },
  { category: "relationship", content: "I’ve questioned whether I push people away unintentionally." },
  { category: "relationship", content: "I’ve wanted deeper connections but avoided vulnerability." },
  { category: "dark", content: "I’ve stayed silent when I should have spoken up." },
  { category: "work", content: "I’ve let opportunities pass because of overthinking." },

  // LATIN AMERICA / OTHERS
  { category: "other", content: "I’ve built strong friendships but still feel lonely sometimes." },
  { category: "dark", content: "I’ve hidden emotions behind humor for years." },
  { category: "dark", content: "I’ve avoided difficult truths because they’re uncomfortable." },
  { category: "other", content: "I’ve made choices I don’t fully understand even now." },
  { category: "relationship", content: "I’ve stayed in situations because leaving felt harder." },
  { category: "dark", content: "I’ve questioned whether I’m growing or just surviving." },
  { category: "dark", content: "I’ve lost parts of myself trying to keep others happy." },
  { category: "other", content: "I’ve struggled with knowing what I truly want." },
  { category: "relationship", content: "I’ve held onto things long after they ended." },
  { category: "other", content: "I’ve felt like I was starting over multiple times." },
  { category: "dark", content: "I’ve had moments where I didn’t recognize myself." },
  { category: "dark", content: "I’ve kept secrets that shaped who I am." },
  { category: "dark", content: "I’ve been afraid of my own thoughts at times." },
  { category: "dark", content: "I’ve wondered if people would stay if they knew everything." },
  { category: "dark", content: "I’ve felt stuck between comfort and change." },
  { category: "dark", content: "I’ve questioned whether I’m living or just existing." },
  { category: "dark", content: "I’ve made peace with things I never got closure on." },
  { category: "dark", content: "I’ve struggled to let go even when I know I should." },
  { category: "dark", content: "I’ve felt like I’m searching for something I can’t define." },
  { category: "dark", content: "I’ve doubted myself more than anyone else ever has." },
  { category: "dark", content: "I’ve tried to be everything for everyone and lost myself." },
  { category: "dark", content: "I’ve hidden pain behind a normal routine." },
  { category: "dark", content: "I’ve wanted to disappear and reset everything." },
  { category: "other", content: "I’ve wondered who I’d be if life went differently." },
  { category: "other", content: "I’m still trying to figure it all out." },

  // BORDERLINE CONTROVERSIAL CONFESSIONS
  { category: "dark", content: "I sometimes stay quiet when someone else is blamed for something I did. Not because I’m proud of it… but because I don’t want to deal with the consequences." },
  { category: "dark", content: "I’ve pretended to like someone just because of what they could do for me." },
  { category: "dark", content: "There’s someone close to me that everyone thinks is a good person. I know a side of them that would completely change how people see them… and I’ve never said a word." },
  { category: "sexual", content: "I’ve been in situations where I knew I was crossing a line, and instead of stopping, I just told myself “it’s not that serious.”" },
  { category: "other", content: "Sometimes I give advice to people that I don’t even follow myself." },
  { category: "dark", content: "I’ve smiled in someone’s face knowing I didn’t trust them at all." },
  { category: "relationship", content: "I’ve stayed in contact with someone not because I care, but because I don’t want them to move on." },
  { category: "dark", content: "I’ve acted like I didn’t notice someone struggling because I didn’t want to get involved." },
  { category: "dark", content: "There are things I’ve done that I would judge someone else for immediately." },
  { category: "dark", content: "I’ve kept secrets that would break friendships if they ever came out." },
  { category: "dark", content: "I’ve let people believe a version of me that isn’t fully true… because it benefits me." },
  { category: "other", content: "Sometimes I think I care more about how things look than how they actually are." },
  { category: "relationship", content: "I’ve ignored red flags because I liked the attention." },
  { category: "dark", content: "I’ve been jealous of people I genuinely care about." },
  { category: "dark", content: "I’ve watched someone mess up their life and didn’t step in, even though I probably could have helped." },
  { category: "relationship", content: "I’ve stayed in situations where I knew I was being used… just because I didn’t want to feel replaceable." },
  { category: "dark", content: "I’ve said things behind someone’s back that I would never say to their face." },
  { category: "relationship", content: "Sometimes I test people just to see if they’ll choose me." },
  { category: "relationship", content: "I’ve kept conversations going with someone I shouldn’t have been talking to… just because it felt good." },
  { category: "dark", content: "I’ve made decisions that I knew would hurt someone, and still went through with them." },
  { category: "relationship", content: "I’ve compared two people in my life and chosen the one who made me feel more important, not the one who treated me better." },
  { category: "dark", content: "I’ve stayed silent in moments where speaking up would have been the right thing to do." },
  { category: "relationship", content: "I’ve enjoyed attention from people I had no intention of committing to." },
  { category: "dark", content: "I’ve let someone take the fall for something we both did." },
  { category: "relationship", content: "I’ve acted like I moved on, but I still check up on them in ways no one would notice." },
  { category: "relationship", content: "I’ve kept someone around as an option." },
  { category: "dark", content: "I’ve felt relief when someone else failed… because it made me feel less behind." },
  { category: "relationship", content: "I’ve ignored messages on purpose just to feel in control." },
  { category: "relationship", content: "I’ve acted like I didn’t care, just to protect my pride." },
  { category: "relationship", content: "I’ve given second chances I didn’t believe in… just to avoid ending things." },
  { category: "other", content: "I’ve been more honest with strangers than with people who actually know me." },
  { category: "relationship", content: "I’ve stayed longer than I should have in situations that were clearly wrong." },
  { category: "dark", content: "I’ve told half-truths instead of full lies so I could still feel like a good person." },
  { category: "relationship", content: "I’ve wanted someone back, not because I loved them… but because I didn’t like how things ended." },
  { category: "relationship", content: "I’ve watched people slowly drift away and didn’t try to stop it." },
  { category: "relationship", content: "I’ve played a role in someone’s life knowing I wasn’t serious about them." },
  { category: "dark", content: "I’ve said “it doesn’t matter” about things that actually mattered a lot." },
  { category: "relationship", content: "I’ve made someone feel secure while I was already emotionally checked out." },
  { category: "other", content: "I’ve avoided people not because they did anything wrong, but because I didn’t want to explain myself." },
  { category: "dark", content: "I’ve stayed quiet about something important just because speaking up would complicate things." },
  { category: "dark", content: "I’ve acted like I didn’t see something I definitely saw." },
  { category: "dark", content: "I’ve judged people for things I secretly relate to." },
  { category: "relationship", content: "I’ve kept conversations going just for the feeling, not the person." },
  { category: "relationship", content: "I’ve distanced myself from someone the moment they got too close." },
  { category: "relationship", content: "I’ve enjoyed being chosen… even when I knew it would hurt someone else." },
  { category: "dark", content: "I’ve told people what they wanted to hear instead of what was true." },
  { category: "dark", content: "I’ve avoided responsibility by pretending I didnt understand." },
  { category: "dark", content: "I’ve been in situations where I knew I was the problem, but I didn’t fix it." },
  { category: "dark", content: "I’ve let misunderstandings happen because correcting them wasn’t in my favor." },
  { category: "relationship", content: "I’ve held onto someone emotionally even after letting them go publicly." }
];
